version: '3'
services:
  backend_server:
    container_name : "api"
    image : "api_server"
    build :
      context : "api"
    ports:
      - 8099:80
    volumes:
      - "./api:/var/www/api"

  mysql:
    container_name : mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exetel
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  frontend_server:
    container_name : "frontend"
    image : "frontend_server"
    build :
      context : "frontend"
    ports:
      - 3000:3000
    volumes:
      - "./frontend:/app/"

volumes:
  mysql-data: